const router = require('express').Router();
const ctrl = require('../controllers/category.controller');
const { auth, authorize } = require('../middleware/auth.middleware');
router.get('/', ctrl.getAll);
router.get('/tree', ctrl.getTree);
router.get('/:id', ctrl.getById);
router.post('/', auth, authorize('manage_categories'), ctrl.create);
router.put('/:id', auth, authorize('manage_categories'), ctrl.update);
router.delete('/:id', auth, authorize('manage_categories'), ctrl.delete);
module.exports = router;
