const express = require("express");
const router = express.Router();
const { authLimiter } = require("../middleware/rateLimiter.middleware");

router.use("/auth", authLimiter, require("./auth.routes"));
router.use("/users", require("./user.routes"));
router.use("/categories", require("./category.routes"));
router.use("/brands", require("./brand.routes"));
router.use("/products", require("./product.routes"));
router.use("/cart", require("./cart.routes"));
router.use("/wishlist", require("./wishlist.routes"));
router.use("/compare", require("./compare.routes"));
router.use("/orders", require("./order.routes"));
router.use("/payments", require("./payment.routes"));
router.use("/coupons", require("./coupon.routes"));
router.use("/reviews", require("./review.routes"));
router.use("/notifications", require("./notification.routes"));
router.use("/search", require("./search.routes"));
router.use("/admin", require("./admin.routes"));
router.use("/export", require("./export.routes"));
router.use("/import", require("./import.routes"));
router.use("/newsletter", require("./newsletter.routes"));
router.use("/settings", require("./settings.routes"));
module.exports = router;
